pipeline {
    agent any
    stages {
        stage ('build nicejob img'){
            steps{
                script{
                    sh 'docker build -t prudhvi120/nicejob prudhvi-app2/'
                }
            }
        }
        stage ('push image to hub'){
            steps{
                script{
                    withCredentials([string(credentialsId: 'docker-credentials', variable: 'docker')]) {
                    sh 'docker login -u prudhvi120 -p ${docker}'
                    }
                    sh 'docker push prudhvi120/nicejob'
                }
            }
        }
    }
}
